/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppSubscriptionRouteImport } from './routes/_app/subscription'
import { Route as AppOrganizationRouteImport } from './routes/_app/organization'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppApiKeysRouteImport } from './routes/_app/api-keys'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppPaidRouteImport } from './routes/_app/_paid'
import { Route as AppAcceptInvitationInvitationIdRouteImport } from './routes/_app/accept-invitation.$invitationId'
import { Route as AppPaidPremiumRouteImport } from './routes/_app/_paid/premium'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppPaidRoute = AppPaidRouteImport.update({
  id: '/_paid',
  getParentRoute: () => AppRoute,
} as any)
const AppAcceptInvitationInvitationIdRoute =
  AppAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPaidPremiumRoute = AppPaidPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppPaidRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRoute
  '/api-keys': typeof AppApiKeysRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/organization': typeof AppOrganizationRoute
  '/subscription': typeof AppSubscriptionRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/premium': typeof AppPaidPremiumRoute
  '/accept-invitation/$invitationId': typeof AppAcceptInvitationInvitationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRoute
  '/api-keys': typeof AppApiKeysRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/organization': typeof AppOrganizationRoute
  '/subscription': typeof AppSubscriptionRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/premium': typeof AppPaidPremiumRoute
  '/accept-invitation/$invitationId': typeof AppAcceptInvitationInvitationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/_paid': typeof AppPaidRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/organization': typeof AppOrganizationRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_paid/premium': typeof AppPaidPremiumRoute
  '/_app/accept-invitation/$invitationId': typeof AppAcceptInvitationInvitationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/api-keys'
    | '/audit'
    | '/billing'
    | '/dashboard'
    | '/notifications'
    | '/organization'
    | '/subscription'
    | '/forgot-password'
    | '/login'
    | '/premium'
    | '/accept-invitation/$invitationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/api-keys'
    | '/audit'
    | '/billing'
    | '/dashboard'
    | '/notifications'
    | '/organization'
    | '/subscription'
    | '/forgot-password'
    | '/login'
    | '/premium'
    | '/accept-invitation/$invitationId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/_paid'
    | '/_app/account'
    | '/_app/api-keys'
    | '/_app/audit'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/organization'
    | '/_app/subscription'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_app/'
    | '/_app/_paid/premium'
    | '/_app/accept-invitation/$invitationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_paid': {
      id: '/_app/_paid'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppPaidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accept-invitation/$invitationId': {
      id: '/_app/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AppAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_paid/premium': {
      id: '/_app/_paid/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AppPaidPremiumRouteImport
      parentRoute: typeof AppPaidRoute
    }
  }
}

interface AppPaidRouteChildren {
  AppPaidPremiumRoute: typeof AppPaidPremiumRoute
}

const AppPaidRouteChildren: AppPaidRouteChildren = {
  AppPaidPremiumRoute: AppPaidPremiumRoute,
}

const AppPaidRouteWithChildren =
  AppPaidRoute._addFileChildren(AppPaidRouteChildren)

interface AppRouteChildren {
  AppPaidRoute: typeof AppPaidRouteWithChildren
  AppAccountRoute: typeof AppAccountRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAcceptInvitationInvitationIdRoute: typeof AppAcceptInvitationInvitationIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPaidRoute: AppPaidRouteWithChildren,
  AppAccountRoute: AppAccountRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppIndexRoute: AppIndexRoute,
  AppAcceptInvitationInvitationIdRoute: AppAcceptInvitationInvitationIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
